name: Run tests

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  release:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn

      - name: Run tests
        run: yarn test
